In [ ]:
# ek bilgi
# mode tekrar sayisi
# mean ortalama sayisi

In [ ]:
import numpy as np
array01=np.arange(0,10)
print(array01)
print(array01[3]) # kacinci indekste ise gosteriyor.If it is at a certain index, it is displayed.
print(array01[1:4]) # araligi belirtilen indeksler arasini yaziyor.The first index in the specified range is included, but the second index is excluded, and the range is printed.
print(array01[4:-1])
print(array01[4:0:-1])
print(array01[4::2])  # 4.indeksten ten baslayip 2ser atlayarak sonuna kadar yazdiriyorIt starts from the 4th index, skips every 2 elements, and prints until the end.

[0 1 2 3 4 5 6 7 8 9]
3
[1 2 3]
[4 5 6 7 8]
[4 3 2 1]
[4 6 8]


In [ ]:
array01=np.arange(0,36).reshape(6,6)
print(array01[0::2,1::2])   # birincisi satirdakiler ikincisi sutundakiler ve ortak olan sayilarla matrisi olustururyor.The first takes the row elements, the second takes the column elements, and the matrix is formed using the common numbers
print(array01[:,::2]) # :=> tum matrisi al demek, ::2 tum matrisi 2 ser atlayarak al demek.
#":=>" → "Take the entire matrix."::2" → "Take the entire matrix, skipping every 2 elements.

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]


In [ ]:
array01=np.arange(0,36).reshape(6,6)
print(array01[:,3])
print(array01[0:2,3:5])
print(array01[2:3,3:4])
print(array01[0::2,1::2])
array01[2,3]=150  # eleman degisikliginde.If we want to change a number in the matrix, we can specify the row and column index and modify it this way.
print(array01[2,3])


[ 3  9 15 21 27 33]
[[ 3  4]
 [ 9 10]]
[[15]]
[[ 1  3  5]
 [13 15 17]
 [25 27 29]]
150


In [ ]:
import numpy as np
np.random.seed(15)  
# seed degeri=> parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor.
#The seed value => If the value inside the parentheses is the same for everyone, it generates the same matrix
# seed matematiksel islemin ortak algoritmasi oluyor
# The seed is the common algorithm of the mathematical operation.
array01=np.random.randint(1,100,size=(5,5)) 

print(array01)
print(array01[(0,1,2,3,4),(4,3,2,1,0)])
print(array01[(1,2,4),(1,1,4)])  # satir ve sutunlardan bulabiliyoruz.We can easily find the elements inside the matrix using rows and columns.




[[73 13  6  1 29]
 [28 72 76 86 48]
 [94 18 32 24 33]
 [63 11 16 69 40]
 [38 20 45 78 61]]
[29 86 32 11 38]
[72 18 61]


In [ ]:

np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
print(array01)
print(array01>30) # 30 dan kucukleri gosterir. true ve false seklinde yanit veriyor.It displays numbers less than 30 and returns answers in the form of True and False.
print(array01<15)  # belirlenilen sayilarin buyuk veya kucuk seklinde boyle bulabiliyoruz.We can find the specified numbers as greater or smaller in this way
a=array01[array01<15]  # sayisal degerlerini gorebilmek icin.To be able to see the numerical values. 
a=array01[array01%2==0]  # cift sayilari icin.For even numbers
a=array01[array01%2==1] # tek sayilar icin .For odd numbers
print(a)



[[ 7 28  8 38]
 [ 2 13  8 20]
 [32 11 20 28]]
[[False False False  True]
 [False False False False]
 [ True False False False]]
[[ True False  True False]
 [ True  True  True False]
 [False  True False False]]
[ 7 13 11]


In [ ]:
# unicast=> birebir iletisim kurma. Unicast → "One-to-one communication."

# multicast=> coklu iletisim kurmak.Multicast → "Many-to-many communication."

# broadcast=> evrensel iletisim kurmak. Broadcast → "Universal communication.



In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
print(array01)
a=array01+5
print(a)
b=array01*3
print(b)
c=array01/2
print(c)
d=array01-20
print(d)
# "We can perform the four basic arithmetic operations on a matrix. The operation is applied to each individual element.




[[ 7 28  8 38]
 [ 2 13  8 20]
 [32 11 20 28]]
[[12 33 13 43]
 [ 7 18 13 25]
 [37 16 25 33]]
[[ 21  84  24 114]
 [  6  39  24  60]
 [ 96  33  60  84]]
[[ 3.5 14.   4.  19. ]
 [ 1.   6.5  4.  10. ]
 [16.   5.5 10.  14. ]]
[[-13   8 -12  18]
 [-18  -7 -12   0]
 [ 12  -9   0   8]]


In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
print(array01)
a=array01[0,:3]=50 # deger degisikligi.Value change
print(array01)
print(a)

[[ 7 28  8 38]
 [ 2 13  8 20]
 [32 11 20 28]]
[[50 50 50 38]
 [ 2 13  8 20]
 [32 11 20 28]]
50


In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
array02=array01+array01 # iki matrisin toplami. The sum of two matrices
array03=array01*5
print(array01)
print(array02)
print(array03)

[[ 7 28  8 38]
 [ 2 13  8 20]
 [32 11 20 28]]
[[14 56 16 76]
 [ 4 26 16 40]
 [64 22 40 56]]
[[ 35 140  40 190]
 [ 10  65  40 100]
 [160  55 100 140]]


In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
array02=np.multiply(array01,3) # carpma islemi yapar. Performs multiplication operation.
print(array01)
print(array02)

[[ 7 28  8 38]
 [ 2 13  8 20]
 [32 11 20 28]]
[[ 21  84  24 114]
 [  6  39  24  60]
 [ 96  33  60  84]]


In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.random.randint(1,50,size=(3,4))
array02=np.multiply(array01,3) 
print(array01.mean())  # aritmetik ortalama. Arithmetic Mean
print(array02.mean())


17.916666666666668
53.75


In [ ]:
np.random.seed(40)  # seed degeri herkeste ayni degerleri gosteriyor. parantez icindeki deger herkesteki degerle ayni olunca ayni matrisi uretiyor
array01=np.arange(0,10)
array02=[100,1200,2627,19387,308,2,8,3030,44] # ilk once dizini kucukten buyuge siralayip orta elemani oyle aliyor. median=>First, it sorts the array in ascending order and then prints the middle element
ortadakideger=np.median(array02)  # ortadaki eleman, eger ortada bir eleman kalmazsa ortada son kalan elemanlarin ortasindaki yani bucuklu sayiyi aliyor.The middle element—if there is no single middle element—takes the average of the last remaining middle elements, resulting in a decimal value
print(array01)
print(ortadakideger)

[0 1 2 3 4 5 6 7 8 9]
308.0


In [ ]:
np.random.seed(40)
array01=np.arange(0,10)
print(np.std(array01)) # standart sapma. Standard deviation

2.8722813232690143
