In [4]:
import numpy as np
np.array


<function numpy.array>

In [5]:
list01=[[0,1,2],[3,4,5],[6,7,8],[9,10,11]]
myarray=np.array(list01)
print(myarray)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
list01=[[[0,1,2],[3,4,5],[6,7,8],[9,10,11]]]
myarray=np.array(list01)
print(myarray)
myarray.ndim # kac boyutlu oldugunu ogreniyoruz.We are learning how many dimensions it has

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


3

In [ ]:
list01=[[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]],[[12,13,14],[15,16,17]]] # 3 boyutlunun gorunumu. three-dimensional appearance
myarray=np.array(list01)
print(myarray)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [ ]:
myarray=np.array([1,2147483647,3],dtype="int32") # 2 uzeri 31 ve -1 i ile max sayiyi yazabiliyoruz.When using a 32-bit signed integer data type, the largest representable number is 2^31 - 1
print(myarray.dtype)
pow(2,31)

int32


2147483648

In [39]:
myarray=np.array([1,2.5,3],dtype="int32")
print(myarray.dtype)
print(myarray)

int32
[1 2 3]


In [40]:
myarray=np.array([1,2,3],dtype="float32")
print(myarray.dtype)
print(myarray)

float32
[1. 2. 3.]


In [ ]:
import numpy as np
myarray=np.array([2.3,"fatma",3]) # U32 str ifade olarak tanimlar.U32 is an alias for the unsigned int data type.
print(myarray.dtype)
print(myarray)

<U32
['2.3' 'fatma' '3']


In [ ]:
myarray=np.array([2.54773678384644,5.6827927826,3,0])
myarray.astype("bool")  # type ni degistiryoruz.We are changing the type



array([ True,  True,  True, False])

In [ ]:
#The resize operation changes the number of rows and columns; it fills missing cells with default values and removes any excess ones
# resize satir sutun degistiryor vermedigimiz degerleri kendisi tamamliyor eger fazlasi varsa da siler
myarray=np.array([[1,2,3],[4,5,6]])
myarray.resize(2,2,3,4) 
print(myarray.ndim)
print(myarray)


4
[[[[1 2 3 4]
   [5 6 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]]


In [ ]:
myarray=np.arange(0,10,2.5)  # verilen araliklarda dizi olusturuyor ve 3. icin kacar kacar olacagi yaziyor."An array is created with the given ranges, and if a step value is provided as the third parameter, intervals are created according to this value
print(myarray)   # ayni sekilde terstende yazabiliyoruz (10,0,-2.5).Similarly, we can write in reverse order as well; for example: range(10, 0, -2.5)


[0.  2.5 5.  7.5]


In [ ]:
myarray=np.linspace(0,10,3) # esit aralikli 3 tane sayi uretiyor. eger 3 u yazmaksak 50 deger veriyor.It generates 3 equally spaced numbers. If we don't specify 3, it gives a value of 50
print(myarray)

[ 0.  5. 10.]


In [ ]:
myarray=np.logspace(0,10,4)  # logaritmik olarak 4 e boluyor. It divides logarithmically by 4.
print(myarray)

[1.00000000e+00 2.15443469e+03 4.64158883e+06 1.00000000e+10]


In [ ]:
myarray=np.zeros((2,2)) # sifirlardan olusan 2 satir 2 sutun olusturdu.It created a 2x2 matrix consisting of zeros
print(myarray)

[[0. 0.]
 [0. 0.]]


In [ ]:
myarray=np.array([[1,2,3],[4,5,6]])
b=np.zeros_like(myarray) # ayni boyutta sifirlardan olusan ayri bir matris olusturuyor,It creates a separate matrix of the same size filled with zeros
print(b)

[[0 0 0]
 [0 0 0]]


In [ ]:
myarray=np.array([[1,2,3],[4,5,6]])
b=np.ones_like(myarray) # ayni boyutta 1`lerden olusan ayri bir matris olusturuyor.It creates a separate matrix of the same size filled with ones
print(b)

[[1 1 1]
 [1 1 1]]


In [ ]:
c=np.ones((5,3))  # 1lerden olusan matris olusturuyor.It creates a separate matrix of the same size filled with ones
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
myarray=np.eye(5) # birim matrisi denilir. kare matrislerde satir ve sutunlar esittir.It creates a unit matrix, where in square matrices, the number of rows and columns are equal.
print(myarray)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
myarray=np.eye(5,4) # birim matrisi denilir. diger matrislerde 2. girilen degr sutun sayisi.It is called the identity matrix. In other matrices, the second entered value is the number of columns
print(myarray)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
myarray=np.full((5,3),45,dtype="U12") # 5e 3 matris yap ve 45 ile doldurur. U lar ile ilk degerini U1 ile iki degerini birden U2 veya iki basamkli sayi yazabilirisn 
myarray=np.full((5,3),"45") # Create a 5x3 matrix filled with 45. You can write the first value as U1, the second value as U2, or use two-digit numbers.
print(myarray.dtype)
print(myarray)

<U2
[['45' '45' '45']
 ['45' '45' '45']
 ['45' '45' '45']
 ['45' '45' '45']
 ['45' '45' '45']]


In [ ]:
# nan oraya ait bir degerin olmadigini ifade eder
# NaN indicates that there is no value for that particular entry.
myarray=np.full((5,3),"nan")
print(myarray)

[['nan' 'nan' 'nan']
 ['nan' 'nan' 'nan']
 ['nan' 'nan' 'nan']
 ['nan' 'nan' 'nan']
 ['nan' 'nan' 'nan']]


In [ ]:
myarray=np.random.rand() # eger belirlemezsek 0 ile 1 arasinda rastgele float bir sayi uretiyor.If not specified, it generates a random number between 0 and 1
print(myarray)


0.10245729440327289


In [ ]:
myarray=np.random.rand(2,3) # 2 ile 3 arasinda rastgele float sayi uretiyor.It generates a random number between 2 and 3
print(myarray)

[[0.01754115 0.57727395 0.40904218]
 [0.51661217 0.79247074 0.56248499]]


In [ ]:
myarray=np.random.rand(2,3,5) # 2 tane 3 ile 5 arasinda rastgele float sayi uretiyor.It generates a random number between 3 and 5
print(myarray)

[[[0.53421219 0.10198078 0.37983413 0.46474175 0.28200977]
  [0.00641771 0.93862073 0.63912864 0.88837743 0.62823747]
  [0.67923847 0.98414549 0.99349006 0.40149434 0.30990273]]

 [[0.18547984 0.68744458 0.96798311 0.27403726 0.64320627]
  [0.62868097 0.0549982  0.34947467 0.21838949 0.22042215]
  [0.30085468 0.79357687 0.09903389 0.98643922 0.46332456]]]


In [ ]:
myarray=np.random.randn(3,3,5) # negatif ve pozitif sayilar uretiyor ve kac tane deger varsa boyut sayisina esit
print(myarray)

[[[-1.22591848 -0.2494108   0.93379381 -2.35835058  0.55326157]
  [ 0.1721252  -1.41913783 -0.35589079 -1.21020591  2.09630803]
  [ 0.44147141  0.10975155  0.3495319  -0.56893574  0.59378977]]

 [[ 0.46117395 -0.47786606  0.12120474 -0.47498354 -0.68389188]
  [-0.49878114 -2.94145097 -0.58114124  0.66765536  1.99398185]
  [ 1.2392088   1.74961391 -0.09833205  1.65379616  0.04744158]]

 [[-0.8655143  -0.42036699 -0.19631101 -0.45272108  1.17987749]
  [ 1.09496671  1.11521403 -0.44134241 -1.97758094  0.22625098]
  [-1.55613909 -0.00765361 -0.38043195  1.38841958  1.62530681]]]


In [ ]:
myarray=np.array([[1,2,3],[4,5,6]])
myarray.mean()
print(myarray.mean()) # aritmatik ortalamasini aliyor.It calculates the arithmetic mean

3.5


In [ ]:
myarray=np.random.randint(4,10)  # hangi sayi araligini yazarsak o aralikta herhangi bir sayi uretiyor.It generates a random number within the specified range
print(myarray)

6


In [ ]:
import numpy as np
myarray=np.random.randint(1,100,5)  # 1 ile 100 arasinda 5 tane sayi ver demek.It generates 5 random numbers between 1 and 100.
print(myarray)

[75 19 69  3 49]


In [ ]:
myarray=np.random.randint(1,100,size=(3,5,2))  # 3 satir 5 sutundan olusan 1 ile 100 arasinda matris olusturuyor.It creates a 3x5 matrix with random numbers between 1 and 100
print(myarray)

[[[95 73]
  [15 99]
  [77 66]
  [48 75]
  [ 6 30]]

 [[59 13]
  [71  7]
  [44 89]
  [86 25]
  [ 6 18]]

 [[83 74]
  [80  5]
  [83 57]
  [15 20]
  [ 4 59]]]


In [ ]:
myarray=np.random.randint(1,100, size=(3,5))  # 1 ile 100 arasinda 3*5 matrisi olustur demek.It creates a 3x5 matrix with random numbers between 1 and 100
print(myarray)
myarray.min() # matrisdeki mini degeri gosteriyor.It shows the minimum value in the matrix
myarray.argmin()# en kucuk degerin indeksini veriyor.It returns the index of the minimum value in the matrix
myarray.max() # matrisdeki max degeri gosterir.It shows the maximum value in the matrix
myarray.argmin() # en buyuk degerinin indeksini verir.It returns the index of the maximum value in the matrix

[[ 3 41 94 77  6]
 [51 27 62 60 47]
 [85 20 79  1 27]]


np.int64(13)

In [ ]:
myarray=np.random.randint(1,100,size=(3,5))  
print(myarray)
myarray.size # toplam eleman sayisi. total number of elements

[[62 43 59 69 64]
 [29 84 41 67 73]
 [87 20  8 33 96]]


15