In [23]:
import numpy as np

In [ ]:
# itemsize bellekte kac byte kapladigini gosterir
#  8 bit  1 byte yapar => 32 bit 4 byte yapar.8 bits make 1 byte; therefore, 32 bits make 4 bytes

In [ ]:
myarray=np.array([1,2,3,4,5,6,7,8,9],dtype=float)
print(myarray.dtype)  # 64 bit 
myarray.itemsize # 8 byte lik bir bellek bulunduruyor.It holds 8 bytes of memory

float64


8

In [15]:
myarray=np.array([1,2,3,4,5,6,7,8,9])
myarray2=myarray.copy()
print(myarray2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
myarray=np.arange(1,16).reshape(5,3)
print(myarray)
changed=myarray.transpose()  # satir sutun sayilarini yer degistirdi yada transppose() yerine T de yazarsak ayni islemi yapar
print(changed) # The column numbers of the DataFrame have swapped places; or if we write T instead of transpose(), we perform the same operation.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]]


In [ ]:
# concatenate ikiden fazla matrisi birlestirmek
# Concatenate more than two matrices.
myarray01=np.arange(1,7)
myarray02=np.arange(7,13)
print(myarray01,myarray02)

birlestirilen=np.concatenate((myarray01,myarray02))
print(birlestirilen)


[1 2 3 4 5 6] [ 7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np
myarray01=np.array([[1,2],[3,4]])
myarray02=np.array([[5,6],[7,8]])
print(myarray01,myarray02)

birlestirilen1=np.concatenate((myarray01,myarray02),axis=0)# iki boyutlu matris toplami. axis=0 demek satir gibi topla demek.Sum of a two-dimensional matrix. Using axis=0 means summing along rows
birlestirilen2=np.concatenate((myarray01,myarray02),axis=1)# axis=1 sutun gibi topla demek.axis=1 sutun gibi topla demek.
# satir ve sutun sayilari birbirine esit olmali
#The number of rows and columns must be equal.

print(birlestirilen1, birlestirilen2)



[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
array03=np.arange(0,10)
print(array03)
bolunen=np.split(array03,5)   # esit parcalar seklinde dizilere  boler. Splits into equal parts as arrays
print(bolunen)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
import numpy as np
array03=np.arange(0,10)
print(array03)
bolunen=np.array_split(array03,4)   # esit olmayan  parcalar seklinde dizilere boler. Splits into unequal parts as arrays
print(bolunen)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]


In [ ]:
import numpy as np
array03=np.array([300,5,678,45,12,1,76,3265,458,np.nan]) # nan deger olmadigi icin en sona yazdiriyor.It writes at the end because there is no NaN value
print(array03)
np.sort(array03) # kucukten buyuge  dogru siraliyor.It sorts in ascending order.


[3.000e+02 5.000e+00 6.780e+02 4.500e+01 1.200e+01 1.000e+00 7.600e+01
 3.265e+03 4.580e+02       nan]


array([1.000e+00, 5.000e+00, 1.200e+01, 4.500e+01, 7.600e+01, 3.000e+02,
       4.580e+02, 6.780e+02, 3.265e+03,       nan])

In [ ]:
array03=np.array([300,5,678,45,12,1,76,3265,458])
print(array03)
np.sort(array03)[::-1]  # buyukten kucuge dogru siraliyor.It sorts in descending order.

[ 300    5  678   45   12    1   76 3265  458]


array([3265,  678,  458,  300,   76,   45,   12,    5,    1])